Names = {
    "family": {"label": {"ar": "الفئة", "en": "type"},
               "values": {"ar": ["عزاب", "عوائل"], "en": ["Singles", "Family"]}},
    "wc": {"label": {"ar": "دورات مياه", "en": "Restrooms"}, "values": {"ar": "%s", "en": "%s"}},
    "type": {"label": {"ar": "الغرض", "en": "Type"},
             "values": {"ar": ["غير محدد", "سكني", "تجاري", "سكني أو تجاري"],
                        "en": ["Not Defiend", "Residential", "Commercial"]}},
    "stairs": {"label": {"ar": "درج صالة", "en": "Stairs"}, "values": {"ar": "%s", "en": "%s"}},
    "driver": {"label": {"ar": "غرفة سائق", "en": "Driver's Room"}, "values": {"ar": "%s", "en": "%s"}},
    "backyard": {"label": {"ar": ["حوش"], "en": ["Backyard"]}, "values": {"ar": "%s", "en": "%s"}},
    "basement": {"label": {"ar": "قبو", 'end': "Basement"}, "values": {"ar": "%s", "en": "%s"}},
    "livings": {"label": {"ar": "الصالات", "en": "Living Rooms"}, "values": {"ar": "%s", "en": "%s"}},
    "ac": {"label": {"ar": "مكيفات", "en": "Airconditioners"}, "values": {"ar": "%s", "en": "%s"}},
    "pool": {"label": {"ar": "مسبح", "en": "Pool"}, "values": {"ar": "%s", "en": "%s"}},
    "ketchen": {"label": {"ar": "مطبخ", "en": "Kitchen"}, "values": {"ar": "%s", "en": "%s"}},
    "lift": {"label": {"ar": "مصعد", "en": "Elevator"}, "values": {"ar": "%s", "en": "%s"}},
    "duplex": {"label": {"ar": "دبلكس", "en": "Duplex"}, "values": {"ar": "%s", "en": "%s"}},
    "fl": {"label": {"ar": "الدور", "en": "Floor"},
           "values": {"ar": ["أرضي", "علوي"], "en": ["Ground", "Upper Ground"]}},
    "apts": {"label": {"ar": "الشقق", "en": "Apartments"}, "values": {"ar": "%s", "en": "%s"}},
    "beds": {"label": {"ar": "غرف النوم", "en": "Bedrooms"}, "values": {"ar": "%s", "en": "%s"}},
    "car_entrance": {"label": {"ar": "مدخل سيارة", "en": "Car Entrance"}, "values": {"ar": "%s", "en": "%s"}},
    "vb": {"label": {"ar": "ملعب كرة طائرة", "en": "Volleyball Playground"}, "values": {"ar": "%s", "en": "%s"}},
    "fb": {"label": {"ar": "ملعب كرة قدم", "en": "Football Playground"}, "values": {"ar": "%s", "en": "%s"}},
    "playground": {"label": {"ar": "ملعب", "en": "Playground"}, "values": {"ar": "%s", "en": "%s"}},
    "family_section": {"label": {"ar": "قسم عوائل", "en": "Family Section"}, "values": {"ar": "%s", "en": "%s"}},
    "maid": {"label": {"ar": "غرفة خادمة", "en": "Maid's Room"}, "values": {"ar": "%s", "en": "%s"}},
    "extra_unit": {"label": {"ar": "ملحق", "en": "Appendix"}, "values": {"ar": "%s", "en": "%s"}},
    "wells": {"label": {"ar": "الآبار", "en": "Wells"}, "values": {"ar": "%s", "en": "%s"}},
    "trees": {"label": {"ar": "النخل", "en": "Palm Trees"}, "values": {"ar": "%s", "en": "%s"}},
    "meter_price": {"label": {"ar": "سعر المتر", "en": "Price Per Meter"},
                    "values": {"ar": "%s ريال", "en": "%s Riyal"}},
    "tent": {"label": {"ar": "مشب", "en": "Tents"}, "values": {"ar": "%s", "en": "%s"}},
    "area": {"label": {"ar": "المساحة", "en": "Area"}, "values": {"ar": "%s م²", "en": "%s"}},
    "age": {"label": {"ar": "عمر العقار", "en": "Real estate age"}, "values": {"ar": ["جديد"], "en": ["New"]}},
    "furnished": {"label": {"ar": "مؤثثة", "en": "Furnished"}, "values": {"ar": "%s", "en": "%s"}},
    "stores": {"label": {"ar": "المحلات", "en": "Stores"}, "values": {"ar": "%s", "en": "%s"}},
    "rooms": {"label": {"ar": "الغرف", "en": "Rooms"}, "values": {"ar": "%s", "en": "%s"}},
    "street_direction": {"label": {"ar": "الواجهة", "en": "Street direction"}, "values": {
        "ar": ["غير محدد", "شمال", "شرق", "غرب", "جنوب", "شمال شرقي", "جنوب شرقي", "جنوب غربي", "شمال غربي", "3 شوارع",
               "4 شوارع"],
        "en": ["Not Defiend", "North", "East", "West", "South", "Northeast", "Southeast", "Southwest", "Northwest",
               "3 Streets", "4 Streets"]}},
    "street_width": {"label": {"ar": "عرض الشارع", "en": "Street width"}, "values": {"ar": "%s م", "en": "%s meter"}},
    "rent_period": {"label": {"ar": "مدة الإيجار", "en": "Rent period"}, "values": {"ar": "%s", "en": "%s"}},
}

FULL_NAMES = {
    "id": {"gql": "Int", "name": {"ar": "رقم الإعلان", "en": "Listing number"}},
    'refresh': {"gql": "Float", "name": {"ar": "وقت اخ تحديث", "en": "Last update"}},
    "category": {"gql": "Int", "name": {"ar": "نوع العقار", "en": "Category"}},
    'has_img': {"gql": "Int", "name": {"ar": "مصورة", "en": "Has image"}},
    'imgs': {"gql": "[String]", "name": {"ar": "صور الإعلان", "en": "Images"}},
    'has_video': {"gql": "Int", "name": {"ar": "فيديو", "en": "Has video"}},
    'videos': {"gql": "[String]", "name": {"ar": "فيديو الإعلان", "en": "videos"}},
    'imgs_desc': {"gql": "[String]", "name": {"ar": "وصف الصور", "en": "Images description"}},
    'status': {"gql": "Int", "name": {"ar": "الحالة", "en": "Status"},
               "values": {"ar": ["متاح", "مغلق", "مغلق قابل للفتح"], "en": ["Available", "Closed", "Re-openable"]}},
    'premium': {"gql": "Int", "name": {"ar": "مدفوع ام مجاني", "en": "Free or premium"},
                "values": {"ar": ["مجاني", "مدفوع"], "en": ["Free", "Paid"]}},
    'price': {"gql": "Float", "name": {"ar": "السعر", "en": "Price"}},
    'wc': {"gql": "Int", "name": {"ar": "عدد دورات المياه", "en": "WC"}},
    'meter_price': {"gql": "Float", "name": {"ar": "سعر المتر", "en": "Meter price"}},
    "age": {"gql": "Int", "name": {"ar": "عمر العقار اقل من", "en": "Age less than"}},
    'area': {"gql": "Float", "name": {"ar": "المساحة", "en": "Area(m2)"}},
    'fl': {"gql": "Int", "name": {"ar": "الدور", "en": "Floor"}},
    'rent_period': {"gql": "Int", "name": {"ar": "مدة الإيجار", "en": "Rent period"}},
    'beds': {"gql": "Int", "name": {"ar": "عدد غرف النوم", "en": "Bed rooms"}},
    'livings': {"gql": "Int", "name": {"ar": "عدد الصالات", "en": "Living rooms"}},
    'ketchen': {"gql": "Int", "name": {"ar": "مطبخ", "en": "Kitchen"}},
    'men_place': {"gql": "Int", "name": {"ar": "مجلس رجال", "en": "Men majles"}},
    'women_place': {"gql": "Int", "name": {"ar": "مجلس نساء", "en": "Women majles"}},
    'apts': {"gql": "Int", "name": {"ar": "عدد الشقق", "en": "Apartments"}},
    'stores': {"gql": "Int", "name": {"ar": "عدد المحلات", "en": "Stores"}},
    'duplex': {"gql": "Int", "name": {"ar": "دوبلكس", "en": "Duplex"}},
    'furnished': {"gql": "Int", "name": {"ar": "مؤثثة", "en": "Furnished"}},
    'driver': {"gql": "Int", "name": {"ar": "غرفة سائق", "en": "Driver room"}},
    'maid': {"gql": "Int", "name": {"ar": "غرفة خادمة", "en": "Maid room"}},
    'basement': {"gql": "Int", "name": {"ar": "قبو", "en": "Basement"}},
    'lift': {"gql": "Int", "name": {"ar": "مصعد", "en": "Lift"}},
    'pool': {"gql": "Int", "name": {"ar": "مسبح", "en": "Pool"}},
    'stairs': {"gql": "Int", "name": {"ar": "درج صالة", "en": "Stairs"}},
    'fb': {"gql": "Int", "name": {"ar": "ملعب كرة قدم", "en": "Football pitch"}},
    'vb': {"gql": "Int", "name": {"ar": "ملعب كرة طائرة", "en": "Volleyball Court"}},
    'tent': {"gql": "Int", "name": {"ar": "بيت شعر", "en": "Tent"}},
    'rooms': {"gql": "Int", "name": {"ar": "عدد الغرف", "en": "Rooms"}},
    'wells': {"gql": "Int", "name": {"ar": "عدد الآبار", "en": "Wells"}},
    'trees': {"gql": "Int", "name": {"ar": "عدد الأشجار", "en": "Trees"}},
    'backyard': {"gql": "Int", "name": {"ar": "حوش", "en": "Backyard"}},
    'playground': {"gql": "Int", "name": {"ar": "ملاهي", "en": "Playground"}},
    'family': {"gql": "Int", "name": {"ar": "عوائل أم عزاب", "en": "Family or single"}},
    'family_section': {"gql": "Int", "name": {"ar": "قسم عوائل", "en": "Family section"}},
    'street_direction': {"gql": "Int", "name": {"ar": "الواجهة", "en": "Street direction"}},
    'street_width': {"gql": "Int", "name": {"ar": "عرض الشارع", "en": "Street width"}},
    'type': {"gql": "Int", "name": {"ar": "سكني أو تجاري", "en": "Residential and commercial"}},
    'car_entrance': {"gql": "Int", "name": {"ar": "مدخل سيارة", "en": "Car entrance"}},
    'ac': {"gql": "Int", "name": {"ar": "مكيف", "en": "Air conditioned"}},
    'location': {"gql": "Location", "name": {"ar": "الموقع", "en": "Location"}},
    'address': {"gql": "String", "name": {"ar": "العنوان", "en": "Status"}},
    'content': {"gql": "String", "name": {"ar": "الوصف", "en": "Address"}},
    'services': {"gql": "[Service]", "name": {"ar": "الخدمات", "en": "Services"}},
    'uri': {"gql": "String", "name": {"ar": "الرابط", "en": "Url"}},
    'city_id': {"gql": "Int", "name": {"ar": "رقم المدينة", "en": "City ID"}},
    'direction_id': {"gql": "Int", "name": {"ar": "رقم الاتجاه", "en": "Direction ID"}},
    'district_id': {"gql": "Int", "name": {"ar": "رقم الحي", "en": "District ID"}},
    'province_id': {"gql": "Int", "name": {"ar": "رقم المحافظة", "en": "Province ID"}},
    'views': {"gql": "Int", "name": {"ar": "المشاهدات", "en": "Views"}},
    'user_name': {"gql": "String", "name": {"ar": "اسم المستخدم", "en": "Username"}},
    'user_id': {"gql": "Int", "name": {"ar": "رقم المستخدم", "en": "User ID"}},
    'user_type': {"gql": "Int", "name": {"ar": "مستخدم ام سمسار", "en": "user or agent"}},
    'extra_unit': {"gql": "Int", "name": {"ar": "ملحق", "en": "Extra unit"}},

    'path': {"gql": "String", "name": {"ar": "المسار", "en": "Path"}},
    'title': {"gql": "String", "name": {"ar": "العنوان", "en": "Title"}},
    'district': {"gql": "String", "name": {"ar": "الحي", "en": "District"}},
    'direction': {"gql": "String", "name": {"ar": "الاتجاه", "en": "Direction"}},
    'city': {"gql": "String", "name": {"ar": "المدينة", "en": "City"}}

}
FULL_NAMES_RE = dict(map(lambda x: (x[1]['name']['ar'],x[0]), FULL_NAMES.items()))


DATA_VALUE = [
    {'elasticName': 'family', 'urlName': 'family', 'fieldName': "الفئة",
     'options': [{'title': 'عوائل', 'value': 1, 'where': {'eq': 1}},
                 {'title': 'عزاب', 'value': 0, 'where': {'eq': 0}}]},

    {'elasticName': 'beds', 'urlName': 'bed_rooms', 'fieldName': "غرف النوم",
     'options': [{'title': 'الكل', 'value': None}, {'title': 'غرفتين', 'value': 2, 'where': {'eq': 2}},
                 {'title': 'ثلاث غرف', 'value': 3, 'where': {'eq': 3}},
                 {'title': 'أربع غرف', 'value': 4, 'where': {'eq': 4}},
                 {'title': 'غرف أكثر', 'value': 5, 'where': {'gt': 5}}]},

    {'elasticName': 'wc', 'urlName': 'wc', 'fieldName': "دورات المياة",
     'options': [{'title': 'الكل', 'value': None}, {'title': 'wc >1', 'value': 1, 'where': {'gte': 1}},
                 {'title': 'wc >2', 'value': 2, 'where': {'gte': 2}},
                 {'title': 'wc >3', 'value': 3, 'where': {'gte': 3}}]},

    {'elasticName': 'price', 'urlName': 'price_category', 'fieldName': "السعر",
     'options': [{'title': 'الكل', 'value': None}, {'title': 'أقل من 1.2 مليون', 'value': 1, 'where': {'lt': 1200000}},
                 {'title': 'أقل من 2 مليون', 'value': 2, 'where': {'gte': 1200000, 'lt': 2000000}},
                 {'title': 'أقل من 5 مليون', 'value': 3, 'where': {'gte': 2000000, 'lt': 5000000}},
                 {'title': 'فلل و قصور فاخرة', 'value': 4, 'where': {'gte': 5000000}}]},

    {'elasticName': 'rent_period', 'urlName': 'rent_type', 'fieldName': "",
     'options': [{'title': 'الكل', 'value': None}, {'title': 'يومي', 'value': 1, 'where': {'eq': 1}},
                 {'title': 'شهري', 'value': 2, 'where': {'eq': 2}}, {'title': 'سنوي', 'value': 3, 'where': {'eq': 3}}]},
    {'elasticName': 'livings', 'urlName': 'living_rooms',
     'options': [{'title': 'الكل', 'value': None}, {'title': 'أكثر من صالة', 'value': 1, 'where': {'gte': 1}},
                 {'title': 'أكثر من صالتين', 'value': 2, 'where': {'gte': 2}},
                 {'title': 'أكثر من ٣ صالات', 'value': 3, 'where': {'gte': 3}}]},
    {'elasticName': 'ketchen', 'urlName': 'kitchen',
     'options': [{'title': 'الكل', 'value': None}, {'title': 'مطبخ موجود', 'value': 1, 'where': {'eq': 1}}]},
    {'elasticName': 'apts', 'urlName': 'apts',
     'options': [{'title': 'الكل', 'value': None}, {'title': 'شقة واحدة', 'value': 1, 'where': {'eq': 1}},
                 {'title': 'شقتان', 'value': 2, 'where': {'eq': 2}}, {'title': '٣ شقق', 'value': 3, 'where': {'eq': 3}},
                 {'title': '٤ شقق', 'value': 4, 'where': {'eq': 4}}]},
    {'elasticName': 'duplex', 'urlName': 'duplex',
     'options': [{'title': 'الكل', 'value': None}, {'title': 'دوبلكس', 'value': 1, 'where': {'eq': 1}}]},
    {'elasticName': 'furnished', 'urlName': 'furnished',
     'options': [{'title': 'الكل', 'value': None}, {'title': 'مؤثثة', 'value': 1, 'where': {'eq': 1}}]},
    {'elasticName': 'driver', 'urlName': 'driver',
     'options': [{'title': 'الكل', 'value': None}, {'title': 'غرفة سائق', 'value': 1, 'where': {'eq': 1}}]},
    {'elasticName': 'maid', 'urlName': 'maid',
     'options': [{'title': 'الكل', 'value': None}, {'title': 'غرفة خادمة', 'value': 1, 'where': {'eq': 1}}]},
    {'elasticName': 'basement', 'urlName': 'basement',
     'options': [{'title': 'الكل', 'value': None}, {'title': 'يوجد قبو', 'value': 1, 'where': {'eq': 1}}]},
    {'elasticName': 'lift', 'urlName': 'lift',
     'options': [{'title': 'الكل', 'value': None}, {'title': 'يوجد مصعد', 'value': 1, 'where': {'eq': 1}}]},
    {'elasticName': 'pool', 'urlName': 'pool',
     'options': [{'title': 'الكل', 'value': None}, {'title': 'يوجد مسبح', 'value': 1, 'where': {'eq': 1}}]},
    {'elasticName': 'stairs', 'urlName': 'stairs',
     'options': [{'title': 'الكل', 'value': None}, {'title': 'يوجد درج صالة', 'value': 1, 'where': {'eq': 1}}]},
    {'elasticName': 'fb', 'urlName': 'football',
     'options': [{'title': 'الكل', 'value': None}, {'title': 'يوجد ملعب كرة قدم', 'value': 1, 'where': {'eq': 1}}]},
    {'elasticName': 'vb', 'urlName': 'volleyball',
     'options': [{'title': 'الكل', 'value': None}, {'title': 'يوجد ملعب كرة طائرة', 'value': 1, 'where': {'eq': 1}}]},
    {'elasticName': 'playground', 'urlName': 'playground',
     'options': [{'title': 'الكل', 'value': None}, {'title': 'يوجد ملاهي', 'value': 1, 'where': {'eq': 1}}]},
    {'elasticName': 'family_section', 'urlName': 'family_section',
     'options': [{'title': 'الكل', 'value': None}, {'title': 'يوجد قسم عوائل', 'value': 1, 'where': {'eq': 1}}]},
    {'elasticName': 'type', 'urlName': 'type', 'options': [{'title': 'سكني', 'value': 1, 'where': {'eq': 1}},
                                                           {'title': 'تجاري', 'value': 2, 'where': {'eq': 2}}]},
    {'elasticName': 'car_entrance', 'urlName': 'car_entrance',
     'options': [{'title': 'الكل', 'value': None}, {'title': 'يوجد مدخل سيارة', 'value': 1, 'where': {'eq': 1}}]},
    {'elasticName': 'ac', 'urlName': 'ac',
     'options': [{'title': 'الكل', 'value': None}, {'title': 'يوجد مكيف', 'value': 1, 'where': {'eq': 1}}]},
    {'elasticName': 'extra_unit', 'urlName': 'extra_unit',
     'options': [{'title': 'الكل', 'value': None}, {'title': 'extra unit available', 'value': 1, 'where': {'eq': 1}}]},

    {'elasticName': 'price', 'urlName': 'price_range', 'fieldName': 'السعر'},
    {'elasticName': 'area', 'urlName': 'area_range', 'fieldName': 'المساحة'},
    {'elasticName': 'fl', 'urlName': 'fl',
     'options': [{'title': 'الكل', 'value': None}, {'title': 'دور أرضي', 'value': 1, 'where': {'eq': 1}}]},
    {'elasticName': 'fl', 'urlName': 'fl',
     'options': [{'title': 'الكل', 'value': None}, {'title': 'دور أرضي', 'value': 1, 'where': {'eq': 1}},
                 {'title': 'دور علوي', 'value': 2, 'where': {'eq': 2}},
                 {'title': 'الدور 3', 'value': 3, 'where': {'eq': 3}},
                 {'title': 'الدور 4', 'value': 4, 'where': {'eq': 4}},
                 {'title': 'الدور 5+ ', 'value': 5, 'where': {'gte': 5}}]},
    {'elasticName': 'age', 'urlName': 'age', 'fieldName': 'العمر',
     'options': [{'title': 'الكل', 'value': None}, {'title': 'أقل من 2 سنة', 'value': 2, 'where': {'lte': 2}},
                 {'title': 'أقل من 5 سنة', 'value': 5, 'where': {'lte': 5}},
                 {'title': 'أقل من 10 سنة', 'value': 10, 'where': {'lte': 10}},
                 {'title': 'أقل من 15 سنة', 'value': 15, 'where': {'lte': 15}}]},
    {'elasticName': 'street_direction', 'urlName': 'street_direction', 'fieldName': 'الواجهة',
     'options': [{'title': 'الكل', 'value': None}, {'title': 'شمال', 'value': 1, 'where': {'eq': 1}},
                 {'title': 'شرق', 'value': 2, 'where': {'eq': 2}}, {'title': 'غرب', 'value': 3, 'where': {'eq': 3}},
                 {'title': 'جنوب', 'value': 4, 'where': {'eq': 4}},
                 {'title': 'شمالي شرقي', 'value': 5, 'where': {'eq': 5}},
                 {'title': 'جنوب شرقي', 'value': 6, 'where': {'eq': 6}},
                 {'title': 'جنوب غربي', 'value': 7, 'where': {'eq': 7}},
                 {'title': 'شمال غربي', 'value': 8, 'where': {'eq': 8}},
                 {'title': '3 شوارع', 'value': 9, 'where': {'eq': 9}},
                 {'title': '4 شوارع', 'value': 10, 'where': {'eq': 10}}]},
    {'elasticName': 'street_width', 'urlName': 'street_width', 'fieldName': 'الشارع',
     'options': [{'title': 'الكل', 'value': None}, {'title': 'أكثر من 5م', 'value': 5, 'where': {'gte': 5}},
                 {'title': 'أكثر من 10م', 'value': 10, 'where': {'gte': 10}},
                 {'title': 'أكثر من 15م', 'value': 15, 'where': {'gte': 15}},
                 {'title': 'أكثر من 20م', 'value': 20, 'where': {'gte': 20}},
                 {'title': 'أكثر من 30م', 'value': 30, 'where': {'gte': 30}},
                 {'title': 'أكثر من 50م', 'value': 50, 'where': {'gte': 50}}]},
    {'elasticName': 'stores', 'urlName': 'stores', 'fieldName': 'المحلات',
     'options': [{'title': 'الكل', 'value': None}, {'title': 'أقل من 4', 'value': 1, 'where': {'lte': 4}},
                 {'title': 'أكثر من 5', 'value': 2, 'where': {'gte': 5}}]},
    {'elasticName': 'meter_price', 'urlName': 'meter_price', 'fieldName': 'المتر',
     'options': [{'title': 'الكل', 'value': None}, {'title': 'أقل من 1500 ريال', 'value': 1, 'where': {'lte': 1500}},
                 {'title': 'أقل من 3 ألف ريال', 'value': 2, 'where': {'lte': 3000}},
                 {'title': 'أقل من 10 ألف ريال', 'value': 3, 'where': {'lte': 10000}},
                 {'title': 'أقل من 20 ألف ريال', 'value': 4, 'where': {'lte': 20000}},
                 {'title': 'أكثر من 20 ألف ريال', 'value': 5, 'where': {'gte': 20000}}]}

]

VALIDATION = {
    'family': {'urlName': 'family', 'fieldName': "الفئة",
               'options': [{'title': 'عوائل', 'value': 1, 'where': {'eq': 1}},
                           {'title': 'عزاب', 'value': 0, 'where': {'eq': 0}}]},
    'has_video': {
        'options': [{'title': 'يوجد فديو', 'value': 1}, {'title': None, 'value': 0}]
    },
    'backyard': {
        'options': [{'title': 'يوجد حوش', 'value': 1}, {'title': None, 'value': 0}]
    },
    'category': {
        'options': [{'title': "شقق للإيجار", 'value': 1}, {'title': "أراضي للبيع", 'value': 2},
                    {'title': "فلل للبيع", 'value': 3}, {'title': "دور للإيجار", 'value': 4},
                    {'title': "فلل للإيجار", 'value': 5}, {'title': "شقق للبيع", 'value': 6}, ]
    },
    'tent': {
        'options': [{'title': 'يوجد بيت شعر', 'value': 1}, {'title': None, 'value': 0}]
    },
    'premium': {
        'options': [{'title': None, 'value': 1}, {'title': None, 'value': 0}]
    },
    'rent_period': {'urlName': 'rent_type', 'fieldName': "",
                    'options': [{'title': 'الكل', 'value': None}, {'title': 'يومي', 'value': 1, 'where': {'eq': 1}},
                                {'title': 'شهري', 'value': 2, 'where': {'eq': 2}},
                                {'title': 'سنوي', 'value': 3, 'where': {'eq': 3}}]},

    'ketchen': {'urlName': 'kitchen',
                'options': [{'title': 'الكل', 'value': None}, {'title': 'مطبخ موجود', 'value': 1, 'where': {'eq': 1}},
                            {'title': None, 'value': 0, 'where': {'eq': 0}}]},

    'duplex': {'urlName': 'duplex',
               'options': [{'title': 'الكل', 'value': None}, {'title': 'دوبلكس', 'value': 1, 'where': {'eq': 1}},
                           {'title': None, 'value': 0, 'where': {'eq': 0}}]},

    'furnished': {'urlName': 'furnished',
                  'options': [{'title': 'الكل', 'value': None}, {'title': 'يوجد مؤثثة', 'value': 1, 'where': {'eq': 1}},
                              {'title': None, 'value': 0, 'where': {'eq': 0}}]},

    'driver': {'urlName': 'driver',
               'options': [{'title': 'الكل', 'value': None}, {'title': 'يوجد غرفة سائق', 'value': 1, 'where': {'eq': 1}},
                           {'title': None, 'value': 0, 'where': {'eq': 0}}]},
    'maid': {'urlName': 'maid',
             'options': [{'title': 'الكل', 'value': None}, {'title': 'يوجد غرفة خادمة', 'value': 1, 'where': {'eq': 1}},
                         {'title': None, 'value': 0, 'where': {'eq': 0}}]},
    'basement': {'urlName': 'basement',
                 'options': [{'title': 'الكل', 'value': None}, {'title': 'يوجد قبو', 'value': 1, 'where': {'eq': 1}},
                             {'title': None, 'value': 0, 'where': {'eq': 0}}]},
    'lift': {'urlName': 'lift',
             'options': [{'title': 'الكل', 'value': None}, {'title': 'يوجد مصعد', 'value': 1, 'where': {'eq': 1}},
                         {'title': None, 'value': 0, 'where': {'eq': 0}}]},
    'pool': {'urlName': 'pool',
             'options': [{'title': 'الكل', 'value': None}, {'title': 'يوجد مسبح', 'value': 1, 'where': {'eq': 1}},
                         {'title': None, 'value': 0, 'where': {'eq': 0}}]},
    'stairs': {'urlName': 'stairs',
               'options': [{'title': 'الكل', 'value': None},
                           {'title': 'يوجد درج صالة', 'value': 1, 'where': {'eq': 1}},
                           {'title': None, 'value': 0, 'where': {'eq': 0}}]},
    'fb': {'urlName': 'football',
           'options': [{'title': 'الكل', 'value': None},
                       {'title': 'يوجد ملعب كرة قدم', 'value': 1, 'where': {'eq': 1}},
                       {'title': None, 'value': 0, 'where': {'eq': 0}}]},
    'vb': {'urlName': 'volleyball',
           'options': [{'title': 'الكل', 'value': None},
                       {'title': 'يوجد ملعب كرة طائرة', 'value': 1, 'where': {'eq': 1}},
                       {'title': None, 'value': 0, 'where': {'eq': 0}}]},
    'playground': {'urlName': 'playground',
                   'options': [{'title': 'الكل', 'value': None},
                               {'title': 'يوجد ملاهي', 'value': 1, 'where': {'eq': 1}},
                               {'title': None, 'value': 0, 'where': {'eq': 0}}]},
    'family_section': {'urlName': 'family_section',
                       'options': [{'title': 'الكل', 'value': None},
                                   {'title': 'يوجد قسم عوائل', 'value': 1, 'where': {'eq': 1}},
                                   {'title': None, 'value': 0, 'where': {'eq': 0}}]},
    'type': {'urlName': 'type', 'options': [{'title': 'سكني', 'value': 1, 'where': {'eq': 1}},
                                            {'title': 'تجاري', 'value': 2, 'where': {'eq': 2}}]},
    'car_entrance': {'urlName': 'car_entrance',
                     'options': [{'title': 'الكل', 'value': None},
                                 {'title': 'يوجد مدخل سيارة', 'value': 1, 'where': {'eq': 1}},
                                 {'title': None, 'value': 0, 'where': {'eq': 0}}]},
    'ac': {'urlName': 'ac',
           'options': [{'title': 'الكل', 'value': None}, {'title': 'يوجد مكيف', 'value': 1, 'where': {'eq': 1}},
                       {'title': None, 'value': 0, 'where': {'eq': 0}}]},
    'extra_unit': {'urlName': 'extra_unit',
                   'options': [{'title': 'الكل', 'value': None},
                               {'title': 'يوجد ملحق', 'value': 1, 'where': {'eq': 1}},
                               {'title': None, 'value': 0, 'where': {'eq': 0}}]},

    'fl': {'urlName': 'fl',
           'options': [{'title': 'الكل', 'value': None}, {'title': 'دور أرضي', 'value': 1, 'where': {'eq': 1}},
                       {'title': 'دور علوي', 'value': 2, 'where': {'eq': 2}},
                       {'title': 'الدور 3', 'value': 3, 'where': {'eq': 3}},
                       {'title': 'الدور 4', 'value': 4, 'where': {'eq': 4}},
                       {'title': 'الدور 5+ ', 'value': 5, 'where': {'gte': 5}}]},

    'street_direction': {'urlName': 'street_direction', 'fieldName': 'الواجهة',
                         'options': [{'title': 'الكل', 'value': None},
                                     {'title': 'شمال', 'value': 1, 'where': {'eq': 1}},
                                     {'title': 'شرق', 'value': 2, 'where': {'eq': 2}},
                                     {'title': 'غرب', 'value': 3, 'where': {'eq': 3}},
                                     {'title': 'جنوب', 'value': 4, 'where': {'eq': 4}},
                                     {'title': 'شمالي شرقي', 'value': 5, 'where': {'eq': 5}},
                                     {'title': 'جنوب شرقي', 'value': 6, 'where': {'eq': 6}},
                                     {'title': 'جنوب غربي', 'value': 7, 'where': {'eq': 7}},
                                     {'title': 'شمال غربي', 'value': 8, 'where': {'eq': 8}},
                                     {'title': '3 شوارع', 'value': 9, 'where': {'eq': 9}},
                                     {'title': '4 شوارع', 'value': 10, 'where': {'eq': 10}}]},

}

OTHER_VALIDATION = {'area': 'م²', 'street_width': "م"}
