js_data = [
    {'elasticName': 'family', 'urlName': 'family', 'fieldName': "الفئة",
     'options': [{'title': 'عوائل', 'value': 1, 'where': {'eq': 1}},
                 {'title': 'عزاب', 'value': 0, 'where': {'eq': 0}}]},

    {'elasticName': 'beds', 'urlName': 'bed_rooms', 'fieldName': "غرف النوم",
     'options': [{'title': 'الكل', 'value': None}, {'title': 'غرفتين', 'value': 2, 'where': {'eq': 2}},
                 {'title': 'ثلاث غرف', 'value': 3, 'where': {'eq': 3}},
                 {'title': 'أربع غرف', 'value': 4, 'where': {'eq': 4}},
                 {'title': 'غرف أكثر', 'value': 5, 'where': {'gt': 5}}]},

    {'elasticName': 'wc', 'urlName': 'wc', 'fieldName': "دورات المياة",
     'options': [{'title': 'الكل', 'value': None}, {'title': 'wc >1', 'value': 1, 'where': {'gte': 1}},
                 {'title': 'wc >2', 'value': 2, 'where': {'gte': 2}},
                 {'title': 'wc >3', 'value': 3, 'where': {'gte': 3}}]},

    {'elasticName': 'price', 'urlName': 'price_category', 'fieldName': "السعر",
     'options': [{'title': 'الكل', 'value': None}, {'title': 'أقل من 1.2 مليون', 'value': 1, 'where': {'lt': 1200000}},
                 {'title': 'أقل من 2 مليون', 'value': 2, 'where': {'gte': 1200000, 'lt': 2000000}},
                 {'title': 'أقل من 5 مليون', 'value': 3, 'where': {'gte': 2000000, 'lt': 5000000}},
                 {'title': 'فلل و قصور فاخرة', 'value': 4, 'where': {'gte': 5000000}}]},

    {'elasticName': 'rent_period', 'urlName': 'rent_type', 'fieldName': "",
     'options': [{'title': 'الكل', 'value': None}, {'title': 'يومي', 'value': 1, 'where': {'eq': 1}},
                 {'title': 'شهري', 'value': 2, 'where': {'eq': 2}}, {'title': 'سنوي', 'value': 3, 'where': {'eq': 3}}]},
    {'elasticName': 'livings', 'urlName': 'living_rooms',
     'options': [{'title': 'الكل', 'value': None}, {'title': 'أكثر من صالة', 'value': 1, 'where': {'gte': 1}},
                 {'title': 'أكثر من صالتين', 'value': 2, 'where': {'gte': 2}},
                 {'title': 'أكثر من ٣ صالات', 'value': 3, 'where': {'gte': 3}}]},
    {'elasticName': 'ketchen', 'urlName': 'kitchen',
     'options': [{'title': 'الكل', 'value': None}, {'title': 'مطبخ موجود', 'value': 1, 'where': {'eq': 1}}]},
    {'elasticName': 'apts', 'urlName': 'apts',
     'options': [{'title': 'الكل', 'value': None}, {'title': 'شقة واحدة', 'value': 1, 'where': {'eq': 1}},
                 {'title': 'شقتان', 'value': 2, 'where': {'eq': 2}}, {'title': '٣ شقق', 'value': 3, 'where': {'eq': 3}},
                 {'title': '٤ شقق', 'value': 4, 'where': {'eq': 4}}]},
    {'elasticName': 'duplex', 'urlName': 'duplex',
     'options': [{'title': 'الكل', 'value': None}, {'title': 'دوبلكس', 'value': 1, 'where': {'eq': 1}}]},
    {'elasticName': 'furnished', 'urlName': 'furnished',
     'options': [{'title': 'الكل', 'value': None}, {'title': 'مؤثثة', 'value': 1, 'where': {'eq': 1}}]},
    {'elasticName': 'driver', 'urlName': 'driver',
     'options': [{'title': 'الكل', 'value': None}, {'title': 'غرفة سائق', 'value': 1, 'where': {'eq': 1}}]},
    {'elasticName': 'maid', 'urlName': 'maid',
     'options': [{'title': 'الكل', 'value': None}, {'title': 'غرفة خادمة', 'value': 1, 'where': {'eq': 1}}]},
    {'elasticName': 'basement', 'urlName': 'basement',
     'options': [{'title': 'الكل', 'value': None}, {'title': 'يوجد قبو', 'value': 1, 'where': {'eq': 1}}]},
    {'elasticName': 'lift', 'urlName': 'lift',
     'options': [{'title': 'الكل', 'value': None}, {'title': 'يوجد مصعد', 'value': 1, 'where': {'eq': 1}}]},
    {'elasticName': 'pool', 'urlName': 'pool',
     'options': [{'title': 'الكل', 'value': None}, {'title': 'يوجد مسبح', 'value': 1, 'where': {'eq': 1}}]},
    {'elasticName': 'stairs', 'urlName': 'stairs',
     'options': [{'title': 'الكل', 'value': None}, {'title': 'يوجد درج صالة', 'value': 1, 'where': {'eq': 1}}]},
    {'elasticName': 'fb', 'urlName': 'football',
     'options': [{'title': 'الكل', 'value': None}, {'title': 'يوجد ملعب كرة قدم', 'value': 1, 'where': {'eq': 1}}]},
    {'elasticName': 'vb', 'urlName': 'volleyball',
     'options': [{'title': 'الكل', 'value': None}, {'title': 'يوجد ملعب كرة طائرة', 'value': 1, 'where': {'eq': 1}}]},
    {'elasticName': 'playground', 'urlName': 'playground',
     'options': [{'title': 'الكل', 'value': None}, {'title': 'يوجد ملاهي', 'value': 1, 'where': {'eq': 1}}]},
    {'elasticName': 'family_section', 'urlName': 'family_section',
     'options': [{'title': 'الكل', 'value': None}, {'title': 'يوجد قسم عوائل', 'value': 1, 'where': {'eq': 1}}]},
    {'elasticName': 'type', 'urlName': 'type', 'options': [{'title': 'سكني', 'value': 1, 'where': {'eq': 1}},
                                                           {'title': 'تجاري', 'value': 2, 'where': {'eq': 2}}]},
    {'elasticName': 'car_entrance', 'urlName': 'car_entrance',
     'options': [{'title': 'الكل', 'value': None}, {'title': 'يوجد مدخل سيارة', 'value': 1, 'where': {'eq': 1}}]},
    {'elasticName': 'ac', 'urlName': 'ac',
     'options': [{'title': 'الكل', 'value': None}, {'title': 'يوجد مكيف', 'value': 1, 'where': {'eq': 1}}]},
    {'elasticName': 'extra_unit', 'urlName': 'extra_unit',
     'options': [{'title': 'الكل', 'value': None}, {'title': 'extra unit available', 'value': 1, 'where': {'eq': 1}}]},

    {'elasticName': 'price', 'urlName': 'price_range', 'fieldName': 'السعر'},
    {'elasticName': 'area', 'urlName': 'area_range', 'fieldName': 'المساحة'},
    {'elasticName': 'fl', 'urlName': 'fl',
     'options': [{'title': 'الكل', 'value': None}, {'title': 'دور أرضي', 'value': 1, 'where': {'eq': 1}}]},
    {'elasticName': 'fl', 'urlName': 'fl',
     'options': [{'title': 'الكل', 'value': None}, {'title': 'دور أرضي', 'value': 1, 'where': {'eq': 1}},
                 {'title': 'دور علوي', 'value': 2, 'where': {'eq': 2}},
                 {'title': 'الدور 3', 'value': 3, 'where': {'eq': 3}},
                 {'title': 'الدور 4', 'value': 4, 'where': {'eq': 4}},
                 {'title': 'الدور 5+ ', 'value': 5, 'where': {'gte': 5}}]},
    {'elasticName': 'age', 'urlName': 'age', 'fieldName': 'العمر',
     'options': [{'title': 'الكل', 'value': None}, {'title': 'أقل من 2 سنة', 'value': 2, 'where': {'lte': 2}},
                 {'title': 'أقل من 5 سنة', 'value': 5, 'where': {'lte': 5}},
                 {'title': 'أقل من 10 سنة', 'value': 10, 'where': {'lte': 10}},
                 {'title': 'أقل من 15 سنة', 'value': 15, 'where': {'lte': 15}}]},
    {'elasticName': 'street_direction', 'urlName': 'street_direction', 'fieldName': 'الواجهة',
     'options': [{'title': 'الكل', 'value': None}, {'title': 'شمال', 'value': 1, 'where': {'eq': 1}},
                 {'title': 'شرق', 'value': 2, 'where': {'eq': 2}}, {'title': 'غرب', 'value': 3, 'where': {'eq': 3}},
                 {'title': 'جنوب', 'value': 4, 'where': {'eq': 4}},
                 {'title': 'شمالي شرقي', 'value': 5, 'where': {'eq': 5}},
                 {'title': 'جنوب شرقي', 'value': 6, 'where': {'eq': 6}},
                 {'title': 'جنوب غربي', 'value': 7, 'where': {'eq': 7}},
                 {'title': 'شمال غربي', 'value': 8, 'where': {'eq': 8}},
                 {'title': '3 شوارع', 'value': 9, 'where': {'eq': 9}},
                 {'title': '4 شوارع', 'value': 10, 'where': {'eq': 10}}]},
    {'elasticName': 'street_width', 'urlName': 'street_width', 'fieldName': 'الشارع',
     'options': [{'title': 'الكل', 'value': None}, {'title': 'أكثر من 5م', 'value': 5, 'where': {'gte': 5}},
                 {'title': 'أكثر من 10م', 'value': 10, 'where': {'gte': 10}},
                 {'title': 'أكثر من 15م', 'value': 15, 'where': {'gte': 15}},
                 {'title': 'أكثر من 20م', 'value': 20, 'where': {'gte': 20}},
                 {'title': 'أكثر من 30م', 'value': 30, 'where': {'gte': 30}},
                 {'title': 'أكثر من 50م', 'value': 50, 'where': {'gte': 50}}]},
    {'elasticName': 'stores', 'urlName': 'stores', 'fieldName': 'المحلات',
     'options': [{'title': 'الكل', 'value': None}, {'title': 'أقل من 4', 'value': 1, 'where': {'lte': 4}},
                 {'title': 'أكثر من 5', 'value': 2, 'where': {'gte': 5}}]},
    {'elasticName': 'meter_price', 'urlName': 'meter_price', 'fieldName': 'المتر',
     'options': [{'title': 'الكل', 'value': None}, {'title': 'أقل من 1500 ريال', 'value': 1, 'where': {'lte': 1500}},
                 {'title': 'أقل من 3 ألف ريال', 'value': 2, 'where': {'lte': 3000}},
                 {'title': 'أقل من 10 ألف ريال', 'value': 3, 'where': {'lte': 10000}},
                 {'title': 'أقل من 20 ألف ريال', 'value': 4, 'where': {'lte': 20000}},
                 {'title': 'أكثر من 20 ألف ريال', 'value': 5, 'where': {'gte': 20000}}]}

]
typ
for key in js_data:
    value = key.get('fieldName', None)
    if not value:
        value = key['options'][1].get('title')
    print(value)
