p = {
    "family": {"label": {"ar": "الفئة", "en": "type"},
               "values": {"ar": ["عزاب", "عوائل"], "en": ["Singles", "Family"]}},
    "wc": {"label": {"ar": "دورات مياه", "en": "Restrooms"}, "values": {"ar": "%s", "en": "%s"}},
    "type": {"label": {"ar": "الغرض", "en": "Type"},
             "values": {"ar": ["غير محدد", "سكني", "تجاري", "سكني أو تجاري"],
                        "en": ["Not Defiend", "Residential", "Commercial"]}},
    "stairs": {"label": {"ar": "درج صالة", "en": "Stairs"}, "values": {"ar": "%s", "en": "%s"}},
    "driver": {"label": {"ar": "غرفة سائق", "en": "Driver's Room"}, "values": {"ar": "%s", "en": "%s"}},
    "backyard": {"label": {"ar": ["حوش"], "en": ["Backyard"]}, "values": {"ar": "%s", "en": "%s"}},
    "basement": {"label": {"ar": "قبو", 'end': "Basement"}, "values": {"ar": "%s", "en": "%s"}},
    "livings": {"label": {"ar": "الصالات", "en": "Living Rooms"}, "values": {"ar": "%s", "en": "%s"}},
    "ac": {"label": {"ar": "مكيفات", "en": "Airconditioners"}, "values": {"ar": "%s", "en": "%s"}},
    "pool": {"label": {"ar": "مسبح", "en": "Pool"}, "values": {"ar": "%s", "en": "%s"}},
    "ketchen": {"label": {"ar": "مطبخ", "en": "Kitchen"}, "values": {"ar": "%s", "en": "%s"}},
    "lift": {"label": {"ar": "مصعد", "en": "Elevator"}, "values": {"ar": "%s", "en": "%s"}},
    "duplex": {"label": {"ar": "دبلكس", "en": "Duplex"}, "values": {"ar": "%s", "en": "%s"}},
    "fl": {"label": {"ar": "الدور", "en": "Floor"},
           "values": {"ar": ["أرضي", "علوي"], "en": ["Ground", "Upper Ground"]}},
    "apts": {"label": {"ar": "الشقق", "en": "Apartments"}, "values": {"ar": "%s", "en": "%s"}},
    "beds": {"label": {"ar": "غرف النوم", "en": "Bedrooms"}, "values": {"ar": "%s", "en": "%s"}},
    "car_entrance": {"label": {"ar": "مدخل سيارة", "en": "Car Entrance"}, "values": {"ar": "%s", "en": "%s"}},
    "vb": {"label": {"ar": "ملعب كرة طائرة", "en": "Volleyball Playground"}, "values": {"ar": "%s", "en": "%s"}},
    "fb": {"label": {"ar": "ملعب كرة قدم", "en": "Football Playground"}, "values": {"ar": "%s", "en": "%s"}},
    "playground": {"label": {"ar": "ملعب", "en": "Playground"}, "values": {"ar": "%s", "en": "%s"}},
    "family_section": {"label": {"ar": "قسم عوائل", "en": "Family Section"}, "values": {"ar": "%s", "en": "%s"}},
    "maid": {"label": {"ar": "غرفة خادمة", "en": "Maid's Room"}, "values": {"ar": "%s", "en": "%s"}},
    "extra_unit": {"label": {"ar": "ملحق", "en": "Appendix"}, "values": {"ar": "%s", "en": "%s"}},
    "wells": {"label": {"ar": "الآبار", "en": "Wells"}, "values": {"ar": "%s", "en": "%s"}},
    "trees": {"label": {"ar": "النخل", "en": "Palm Trees"}, "values": {"ar": "%s", "en": "%s"}},
    "meter_price": {"label": {"ar": "سعر المتر", "en": "Price Per Meter"},
                    "values": {"ar": "%s ريال", "en": "%s Riyal"}},
    "tent": {"label": {"ar": "مشب", "en": "Tents"}, "values": {"ar": "%s", "en": "%s"}},
    "area": {"label": {"ar": "المساحة", "en": "Area"}, "values": {"ar": "%s م²", "en": "%s"}},
    "age": {"label": {"ar": "عمر العقار", "en": "Real estate age"}, "values": {"ar": ["جديد"], "en": ["New"]}},
    "furnished": {"label": {"ar": "مؤثثة", "en": "Furnished"}, "values": {"ar": "%s", "en": "%s"}},
    "stores": {"label": {"ar": "المحلات", "en": "Stores"}, "values": {"ar": "%s", "en": "%s"}},
    "rooms": {"label": {"ar": "الغرف", "en": "Rooms"}, "values": {"ar": "%s", "en": "%s"}},
    "street_direction": {"label": {"ar": "الواجهة", "en": "Street direction"}, "values": {
        "ar": ["غير محدد", "شمال", "شرق", "غرب", "جنوب", "شمال شرقي", "جنوب شرقي", "جنوب غربي", "شمال غربي", "3 شوارع",
               "4 شوارع"],
        "en": ["Not Defiend", "North", "East", "West", "South", "Northeast", "Southeast", "Southwest", "Northwest",
               "3 Streets", "4 Streets"]}},
    "street_width": {"label": {"ar": "عرض الشارع", "en": "Street width"}, "values": {"ar": "%s م", "en": "%s meter"}},
    "rent_period": {"label": {"ar": "مدة الإيجار", "en": "Rent period"}, "values": {"ar": "%s", "en": "%s"}},
}

# category
_ = [{"title": "شقق للإيجار", "pathname": "/شقق-للإيجار", "category": 1},
     {"title": "أراضي للبيع", "pathname": "/أراضي-للبيع", "category": 2},
     {"title": "فلل للبيع", "pathname": "/فلل-للبيع", "category": 3},
     {"title": "دور للإيجار", "pathname": "/دور-للإيجار", "category": 4},
     {"title": "فلل للإيجار", "pathname": "/فلل-للإيجار", "category": 5},
     {"title": "شقق للبيع", "pathname": "/شقق-للبيع", "category": 6}]