# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ui.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *

import ui_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1091, 700)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setWindowTitle(u"")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(-1, -1, 1091, 681))
        sizePolicy1 = QSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.MinimumExpanding)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy1)
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.pushButton_4 = QPushButton(self.frame)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(820, 220, 231, 41))
        font = QFont()
        font.setFamily(u"Almarai")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_4.setStyleSheet(u"background-color: rgb(123, 123, 123);\n"
"border-radius: 20px")
        self.pushButton_4.setIconSize(QSize(200, 50))
        self.label_3 = QLabel(self.frame)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(770, 110, 321, 491))
        self.label_3.setStyleSheet(u"background-color: rgb(244, 242, 243);\n"
"\n"
"\n"
"")
        self.pushButton_2 = QPushButton(self.frame)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(820, 470, 231, 41))
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet(u"color: rgb(0, 0, 0);\n"
"background-color: rgb(123, 123, 123);\n"
"border-radius: 20px\n"
"\n"
"")
        self.label = QLabel(self.frame)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(0, 0, 1091, 111))
        self.label.setMinimumSize(QSize(0, 0))
        self.label.setStyleSheet(u"background-color: rgb(98, 98, 98);\n"
"")
        self.pushButton_24 = QPushButton(self.frame)
        self.pushButton_24.setObjectName(u"pushButton_24")
        self.pushButton_24.setGeometry(QRect(820, 380, 231, 41))
        font1 = QFont()
        font1.setFamily(u"Almarai")
        font1.setPointSize(12)
        font1.setBold(True)
        font1.setWeight(75)
        self.pushButton_24.setFont(font1)
        self.pushButton_24.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_24.setStyleSheet(u"color: rgb(0, 0, 0);\n"
"background-color: rgb(123, 123, 123);\n"
"border-radius: 20px\n"
"\n"
"")
        self.pushButton_3 = QPushButton(self.frame)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(820, 550, 231, 41))
        self.pushButton_3.setFont(font)
        self.pushButton_3.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet(u"color: rgb(0, 0, 0);\n"
"background-color: rgb(123, 123, 123);\n"
"border-radius: 20px")
        self.pushButton_48 = QPushButton(self.frame)
        self.pushButton_48.setObjectName(u"pushButton_48")
        self.pushButton_48.setGeometry(QRect(820, 140, 231, 41))
        self.pushButton_48.setFont(font)
        self.pushButton_48.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_48.setStyleSheet(u"background-color: rgb(123, 123, 123);\n"
"border-radius: 20px")
        self.pushButton_48.setIconSize(QSize(200, 50))
        self.pushButton_5 = QPushButton(self.frame)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(710, 30, 311, 51))
        font2 = QFont()
        font2.setFamily(u"Almarai")
        font2.setPointSize(19)
        font2.setBold(True)
        font2.setWeight(75)
        self.pushButton_5.setFont(font2)
        self.pushButton_5.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_5.setStyleSheet(u"border-radius: 20px;\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"")
        icon = QIcon()
        icon.addFile(u":/newPrefix/Desktop/like pro/\u0641\u062a\u062d \u0645\u0648\u0642\u0639 \u0627\u0644\u0648\u0627\u062a\u0633\u0627\u0628.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton_5.setIcon(icon)
        self.pushButton_5.setIconSize(QSize(283, 65))
        self.tabWidget = QTabWidget(self.frame)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 110, 801, 571))
        palette = QPalette()
        brush = QBrush(QColor(192, 192, 192, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(48, 47, 47, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(255, 255, 255, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Light, brush2)
        brush3 = QBrush(QColor(238, 238, 238, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        brush4 = QBrush(QColor(110, 110, 110, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Dark, brush4)
        brush5 = QBrush(QColor(147, 147, 147, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        palette.setBrush(QPalette.Active, QPalette.BrightText, brush2)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette.setBrush(QPalette.Active, QPalette.Window, brush1)
        brush6 = QBrush(QColor(0, 0, 0, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush6)
        brush7 = QBrush(QColor(61, 142, 201, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Highlight, brush7)
        palette.setBrush(QPalette.Active, QPalette.HighlightedText, brush6)
        palette.setBrush(QPalette.Active, QPalette.AlternateBase, brush3)
        brush8 = QBrush(QColor(255, 255, 220, 255))
        brush8.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush8)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette.setBrush(QPalette.Inactive, QPalette.BrightText, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Shadow, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.Highlight, brush7)
        palette.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush8)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush6)
        brush9 = QBrush(QColor(128, 128, 128, 255))
        brush9.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush9)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush9)
        palette.setBrush(QPalette.Disabled, QPalette.BrightText, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush9)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Shadow, brush6)
        palette.setBrush(QPalette.Disabled, QPalette.Highlight, brush7)
        palette.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush6)
        brush10 = QBrush(QColor(221, 221, 221, 255))
        brush10.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush10)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush8)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush6)
        self.tabWidget.setPalette(palette)
        self.tabWidget.setMouseTracking(False)
        self.tabWidget.setFocusPolicy(Qt.TabFocus)
#if QT_CONFIG(tooltip)
        self.tabWidget.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet(u"\n"
"QTabWidget::pane {\n"
"    border: 1px solid #76797C;\n"
"    padding: 5px;\n"
"    margin: 0px;\n"
"	\n"
"	background-color: rgb(123, 123, 123);\n"
"}\n"
"QTabWidget::tab-bar {\n"
"    left: 5px; /* move to the right by 5px */\n"
"}\n"
"")
        self.tabWidget.setTabPosition(QTabWidget.North)
        self.tabWidget.setElideMode(Qt.ElideLeft)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(True)
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.label_5 = QLabel(self.tab)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 10, 561, 291))
        self.label_5.setStyleSheet(u"image: url(:/newPrefix/like pro/logo middle.png);")
        self.lineEdit_4 = QLineEdit(self.tab)
        self.lineEdit_4.setObjectName(u"lineEdit_4")
        self.lineEdit_4.setGeometry(QRect(50, 360, 491, 41))
        self.lineEdit_4.setFont(font1)
        self.lineEdit_4.setCursorMoveStyle(Qt.LogicalMoveStyle)
        self.lineEdit_4.setClearButtonEnabled(True)
        self.pushButton_49 = QPushButton(self.tab)
        self.pushButton_49.setObjectName(u"pushButton_49")
        self.pushButton_49.setGeometry(QRect(560, 360, 151, 41))
        font3 = QFont()
        font3.setFamily(u"Almarai")
        font3.setPointSize(17)
        font3.setBold(True)
        font3.setWeight(75)
        self.pushButton_49.setFont(font3)
        self.pushButton_49.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_49.setStyleSheet(u"border-radius: 20px;\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"")
        self.pushButton_49.setIcon(icon)
        self.pushButton_49.setIconSize(QSize(283, 65))
        self.lineEdit_5 = QLineEdit(self.tab)
        self.lineEdit_5.setObjectName(u"lineEdit_5")
        self.lineEdit_5.setEnabled(False)
        self.lineEdit_5.setGeometry(QRect(50, 420, 491, 41))
        self.lineEdit_5.setFont(font1)
        self.lineEdit_5.setAutoFillBackground(False)
        self.lineEdit_5.setInputMethodHints(Qt.ImhNone)
        self.label_18 = QLabel(self.tab)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(550, 420, 191, 41))
        self.label_18.setFont(font3)
        self.label_18.setLayoutDirection(Qt.LeftToRight)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.tableWidget_2 = QTableWidget(self.tab_2)
        if (self.tableWidget_2.columnCount() < 1):
            self.tableWidget_2.setColumnCount(1)
        __qtablewidgetitem = QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, __qtablewidgetitem)
        self.tableWidget_2.setObjectName(u"tableWidget_2")
        self.tableWidget_2.setGeometry(QRect(30, 40, 181, 201))
        self.tableWidget_2.setLayoutDirection(Qt.LeftToRight)
        self.tableWidget_2.setAutoFillBackground(False)
        self.tableWidget_2.setStyleSheet(u"border: none;\n"
"background-color: #d7d6d5;\n"
"")
        self.tableWidget_2.setTextElideMode(Qt.ElideRight)
        self.pushButton_9 = QPushButton(self.tab_2)
        self.pushButton_9.setObjectName(u"pushButton_9")
        self.pushButton_9.setGeometry(QRect(100, 260, 121, 41))
        font4 = QFont()
        font4.setFamily(u"Almarai")
        font4.setPointSize(11)
        font4.setBold(True)
        font4.setWeight(75)
        self.pushButton_9.setFont(font4)
        self.pushButton_9.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_9.setStyleSheet(u"border-radius: 20px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.pushButton_9.setIconSize(QSize(200, 50))
        self.pushButton_7 = QPushButton(self.tab_2)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setGeometry(QRect(640, 40, 131, 41))
        self.pushButton_7.setFont(font4)
        self.pushButton_7.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_7.setStyleSheet(u"border-radius: 20px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.pushButton_7.setIconSize(QSize(200, 50))
        self.pushButton_10 = QPushButton(self.tab_2)
        self.pushButton_10.setObjectName(u"pushButton_10")
        self.pushButton_10.setGeometry(QRect(640, 110, 131, 41))
        self.pushButton_10.setFont(font4)
        self.pushButton_10.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_10.setStyleSheet(u"border-radius: 20px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.pushButton_10.setIconSize(QSize(200, 50))
        self.pushButton_11 = QPushButton(self.tab_2)
        self.pushButton_11.setObjectName(u"pushButton_11")
        self.pushButton_11.setGeometry(QRect(640, 180, 131, 41))
        self.pushButton_11.setFont(font4)
        self.pushButton_11.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_11.setStyleSheet(u"border-radius: 20px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.pushButton_11.setIconSize(QSize(200, 50))
        self.pushButton_12 = QPushButton(self.tab_2)
        self.pushButton_12.setObjectName(u"pushButton_12")
        self.pushButton_12.setGeometry(QRect(640, 250, 131, 41))
        self.pushButton_12.setFont(font4)
        self.pushButton_12.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_12.setStyleSheet(u"border-radius: 20px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.pushButton_12.setIconSize(QSize(200, 50))
        self.pushButton_13 = QPushButton(self.tab_2)
        self.pushButton_13.setObjectName(u"pushButton_13")
        self.pushButton_13.setGeometry(QRect(330, 440, 61, 41))
        font5 = QFont()
        font5.setFamily(u"Almarai")
        font5.setPointSize(10)
        font5.setBold(True)
        font5.setWeight(75)
        self.pushButton_13.setFont(font5)
        self.pushButton_13.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_13.setStyleSheet(u"border-radius: 20px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.pushButton_13.setIconSize(QSize(200, 50))
        self.pushButton_14 = QPushButton(self.tab_2)
        self.pushButton_14.setObjectName(u"pushButton_14")
        self.pushButton_14.setGeometry(QRect(20, 260, 71, 41))
        self.pushButton_14.setFont(font4)
        self.pushButton_14.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_14.setStyleSheet(u"border-radius: 20px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.pushButton_14.setIconSize(QSize(200, 50))
        self.tableWidget_8 = QTableWidget(self.tab_2)
        if (self.tableWidget_8.columnCount() < 1):
            self.tableWidget_8.setColumnCount(1)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(0, __qtablewidgetitem1)
        self.tableWidget_8.setObjectName(u"tableWidget_8")
        self.tableWidget_8.setGeometry(QRect(240, 40, 161, 391))
        self.tableWidget_8.setLayoutDirection(Qt.LeftToRight)
        self.tableWidget_8.setAutoFillBackground(False)
        self.tableWidget_8.setStyleSheet(u"border: none;\n"
"background-color: #d7d6d5;\n"
"")
        self.tableWidget_8.setTextElideMode(Qt.ElideRight)
        self.tableWidget_9 = QTableWidget(self.tab_2)
        if (self.tableWidget_9.columnCount() < 1):
            self.tableWidget_9.setColumnCount(1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.tableWidget_9.setHorizontalHeaderItem(0, __qtablewidgetitem2)
        self.tableWidget_9.setObjectName(u"tableWidget_9")
        self.tableWidget_9.setGeometry(QRect(420, 40, 161, 391))
        self.tableWidget_9.setLayoutDirection(Qt.LeftToRight)
        self.tableWidget_9.setAutoFillBackground(False)
        self.tableWidget_9.setStyleSheet(u"border: none;\n"
"background-color: #d7d6d5;\n"
"")
        self.tableWidget_9.setTextElideMode(Qt.ElideRight)
        self.pushButton_23 = QPushButton(self.tab_2)
        self.pushButton_23.setObjectName(u"pushButton_23")
        self.pushButton_23.setGeometry(QRect(250, 440, 61, 41))
        self.pushButton_23.setFont(font5)
        self.pushButton_23.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_23.setStyleSheet(u"border-radius: 20px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.pushButton_23.setIconSize(QSize(200, 50))
        self.pushButton_36 = QPushButton(self.tab_2)
        self.pushButton_36.setObjectName(u"pushButton_36")
        self.pushButton_36.setGeometry(QRect(520, 440, 61, 41))
        self.pushButton_36.setFont(font5)
        self.pushButton_36.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_36.setStyleSheet(u"border-radius: 20px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.pushButton_36.setIconSize(QSize(200, 50))
        self.pushButton_37 = QPushButton(self.tab_2)
        self.pushButton_37.setObjectName(u"pushButton_37")
        self.pushButton_37.setGeometry(QRect(440, 440, 61, 41))
        self.pushButton_37.setFont(font5)
        self.pushButton_37.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_37.setStyleSheet(u"border-radius: 20px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.pushButton_37.setIconSize(QSize(200, 50))
        self.label_8 = QLabel(self.tab_2)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(40, 10, 141, 21))
        self.label_8.setFont(font4)
        self.label_8.setLayoutDirection(Qt.LeftToRight)
        self.label_9 = QLabel(self.tab_2)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(250, 10, 121, 21))
        self.label_9.setFont(font4)
        self.label_9.setLayoutDirection(Qt.LeftToRight)
        self.label_10 = QLabel(self.tab_2)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(420, 10, 141, 21))
        self.label_10.setFont(font4)
        self.label_10.setLayoutDirection(Qt.LeftToRight)
        self.textEdit_3 = QTextEdit(self.tab_2)
        self.textEdit_3.setObjectName(u"textEdit_3")
        self.textEdit_3.setGeometry(QRect(30, 310, 181, 121))
        self.pushButton_42 = QPushButton(self.tab_2)
        self.pushButton_42.setObjectName(u"pushButton_42")
        self.pushButton_42.setGeometry(QRect(40, 440, 71, 41))
        self.pushButton_42.setFont(font5)
        self.pushButton_42.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_42.setStyleSheet(u"border-radius: 20px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.pushButton_42.setIconSize(QSize(200, 50))
        self.pushButton_43 = QPushButton(self.tab_2)
        self.pushButton_43.setObjectName(u"pushButton_43")
        self.pushButton_43.setGeometry(QRect(130, 440, 71, 41))
        self.pushButton_43.setFont(font5)
        self.pushButton_43.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_43.setStyleSheet(u"border-radius: 20px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.pushButton_43.setIconSize(QSize(200, 50))
        self.pushButton_46 = QPushButton(self.tab_2)
        self.pushButton_46.setObjectName(u"pushButton_46")
        self.pushButton_46.setGeometry(QRect(590, 380, 191, 41))
        self.pushButton_46.setFont(font4)
        self.pushButton_46.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_46.setStyleSheet(u"border-radius: 20px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.pushButton_46.setIconSize(QSize(200, 50))
        self.lineEdit_2 = QLineEdit(self.tab_2)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(590, 330, 131, 31))
        self.label_16 = QLabel(self.tab_2)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(680, 330, 101, 21))
        self.label_16.setFont(font4)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.textEdit_2 = QTextEdit(self.tab_3)
        self.textEdit_2.setObjectName(u"textEdit_2")
        self.textEdit_2.setGeometry(QRect(450, 50, 311, 121))
        self.textEdit_2.setLayoutDirection(Qt.RightToLeft)
        self.pushButton_28 = QPushButton(self.tab_3)
        self.pushButton_28.setObjectName(u"pushButton_28")
        self.pushButton_28.setGeometry(QRect(630, 180, 121, 41))
        self.pushButton_28.setFont(font4)
        self.pushButton_28.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_28.setStyleSheet(u"border-radius: 20px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.pushButton_28.setIconSize(QSize(200, 50))
        self.radioButton_3 = QRadioButton(self.tab_3)
        self.radioButton_3.setObjectName(u"radioButton_3")
        self.radioButton_3.setGeometry(QRect(630, 20, 82, 17))
        self.radioButton_3.setLayoutDirection(Qt.RightToLeft)
        self.tableWidget_6 = QTableWidget(self.tab_3)
        if (self.tableWidget_6.columnCount() < 2):
            self.tableWidget_6.setColumnCount(2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(0, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(1, __qtablewidgetitem4)
        self.tableWidget_6.setObjectName(u"tableWidget_6")
        self.tableWidget_6.setGeometry(QRect(10, 20, 271, 351))
        self.tableWidget_6.setLayoutDirection(Qt.RightToLeft)
        self.tableWidget_6.setAutoFillBackground(False)
        self.tableWidget_6.setStyleSheet(u"border: none;\n"
"background-color: #d7d6d5;\n"
"")
        self.tableWidget_6.setTextElideMode(Qt.ElideRight)
        self.pushButton_29 = QPushButton(self.tab_3)
        self.pushButton_29.setObjectName(u"pushButton_29")
        self.pushButton_29.setGeometry(QRect(140, 380, 131, 41))
        self.pushButton_29.setFont(font4)
        self.pushButton_29.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_29.setStyleSheet(u"border-radius: 20px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.pushButton_29.setIconSize(QSize(200, 50))
        self.tableWidget_7 = QTableWidget(self.tab_3)
        if (self.tableWidget_7.columnCount() < 4):
            self.tableWidget_7.setColumnCount(4)
        __qtablewidgetitem5 = QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(0, __qtablewidgetitem5)
        __qtablewidgetitem6 = QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(1, __qtablewidgetitem6)
        __qtablewidgetitem7 = QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(2, __qtablewidgetitem7)
        __qtablewidgetitem8 = QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(3, __qtablewidgetitem8)
        self.tableWidget_7.setObjectName(u"tableWidget_7")
        self.tableWidget_7.setGeometry(QRect(450, 230, 311, 191))
        self.tableWidget_7.setLayoutDirection(Qt.RightToLeft)
        self.tableWidget_7.setAutoFillBackground(False)
        self.tableWidget_7.setStyleSheet(u"border: none;\n"
"background-color: #d7d6d5;\n"
"")
        self.tableWidget_7.setTextElideMode(Qt.ElideRight)
        self.pushButton_30 = QPushButton(self.tab_3)
        self.pushButton_30.setObjectName(u"pushButton_30")
        self.pushButton_30.setGeometry(QRect(300, 170, 131, 41))
        self.pushButton_30.setFont(font4)
        self.pushButton_30.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_30.setStyleSheet(u"border-radius: 20px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.pushButton_30.setIconSize(QSize(200, 50))
        self.radioButton_4 = QRadioButton(self.tab_3)
        self.radioButton_4.setObjectName(u"radioButton_4")
        self.radioButton_4.setGeometry(QRect(500, 20, 82, 17))
        self.radioButton_4.setLayoutDirection(Qt.RightToLeft)
        self.pushButton_31 = QPushButton(self.tab_3)
        self.pushButton_31.setObjectName(u"pushButton_31")
        self.pushButton_31.setGeometry(QRect(300, 240, 131, 41))
        self.pushButton_31.setFont(font4)
        self.pushButton_31.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_31.setStyleSheet(u"border-radius: 20px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.pushButton_31.setIconSize(QSize(200, 50))
        self.pushButton_32 = QPushButton(self.tab_3)
        self.pushButton_32.setObjectName(u"pushButton_32")
        self.pushButton_32.setGeometry(QRect(470, 180, 121, 41))
        self.pushButton_32.setFont(font4)
        self.pushButton_32.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_32.setStyleSheet(u"border-radius: 20px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.pushButton_32.setIconSize(QSize(200, 50))
        self.pushButton_33 = QPushButton(self.tab_3)
        self.pushButton_33.setObjectName(u"pushButton_33")
        self.pushButton_33.setGeometry(QRect(300, 310, 131, 41))
        self.pushButton_33.setFont(font4)
        self.pushButton_33.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_33.setStyleSheet(u"border-radius: 20px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.pushButton_33.setIconSize(QSize(200, 50))
        self.pushButton_34 = QPushButton(self.tab_3)
        self.pushButton_34.setObjectName(u"pushButton_34")
        self.pushButton_34.setGeometry(QRect(20, 380, 111, 41))
        self.pushButton_34.setFont(font4)
        self.pushButton_34.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_34.setStyleSheet(u"border-radius: 20px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.pushButton_34.setIconSize(QSize(200, 50))
        self.pushButton_35 = QPushButton(self.tab_3)
        self.pushButton_35.setObjectName(u"pushButton_35")
        self.pushButton_35.setGeometry(QRect(300, 380, 131, 41))
        self.pushButton_35.setFont(font4)
        self.pushButton_35.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_35.setStyleSheet(u"border-radius: 20px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.pushButton_35.setIconSize(QSize(200, 50))
        self.spinBox = QSpinBox(self.tab_3)
        self.spinBox.setObjectName(u"spinBox")
        self.spinBox.setGeometry(QRect(300, 130, 51, 22))
        self.label_6 = QLabel(self.tab_3)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(320, 70, 121, 21))
        self.label_6.setFont(font4)
        self.label_19 = QLabel(self.tab_3)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(390, 100, 41, 21))
        self.label_19.setFont(font4)
        self.label_20 = QLabel(self.tab_3)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(290, 100, 41, 21))
        self.label_20.setFont(font4)
        self.spinBox_3 = QSpinBox(self.tab_3)
        self.spinBox_3.setObjectName(u"spinBox_3")
        self.spinBox_3.setGeometry(QRect(390, 130, 51, 22))
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_7 = QWidget()
        self.tab_7.setObjectName(u"tab_7")
        self.tableWidget_3 = QTableWidget(self.tab_7)
        if (self.tableWidget_3.columnCount() < 2):
            self.tableWidget_3.setColumnCount(2)
        __qtablewidgetitem9 = QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, __qtablewidgetitem9)
        __qtablewidgetitem10 = QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, __qtablewidgetitem10)
        self.tableWidget_3.setObjectName(u"tableWidget_3")
        self.tableWidget_3.setGeometry(QRect(10, 20, 271, 351))
        self.tableWidget_3.setLayoutDirection(Qt.LeftToRight)
        self.tableWidget_3.setAutoFillBackground(False)
        self.tableWidget_3.setStyleSheet(u"border: none;\n"
"background-color: #d7d6d5;\n"
"")
        self.tableWidget_3.setTextElideMode(Qt.ElideRight)
        self.pushButton_15 = QPushButton(self.tab_7)
        self.pushButton_15.setObjectName(u"pushButton_15")
        self.pushButton_15.setGeometry(QRect(300, 170, 131, 41))
        self.pushButton_15.setFont(font4)
        self.pushButton_15.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_15.setStyleSheet(u"border-radius: 20px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.pushButton_15.setIconSize(QSize(200, 50))
        self.pushButton_16 = QPushButton(self.tab_7)
        self.pushButton_16.setObjectName(u"pushButton_16")
        self.pushButton_16.setGeometry(QRect(300, 310, 131, 41))
        self.pushButton_16.setFont(font4)
        self.pushButton_16.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_16.setStyleSheet(u"border-radius: 20px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.pushButton_16.setIconSize(QSize(200, 50))
        self.pushButton_17 = QPushButton(self.tab_7)
        self.pushButton_17.setObjectName(u"pushButton_17")
        self.pushButton_17.setGeometry(QRect(300, 240, 131, 41))
        self.pushButton_17.setFont(font4)
        self.pushButton_17.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_17.setStyleSheet(u"border-radius: 20px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.pushButton_17.setIconSize(QSize(200, 50))
        self.pushButton_18 = QPushButton(self.tab_7)
        self.pushButton_18.setObjectName(u"pushButton_18")
        self.pushButton_18.setGeometry(QRect(20, 380, 111, 41))
        self.pushButton_18.setFont(font4)
        self.pushButton_18.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_18.setStyleSheet(u"border-radius: 20px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.pushButton_18.setIconSize(QSize(200, 50))
        self.pushButton_19 = QPushButton(self.tab_7)
        self.pushButton_19.setObjectName(u"pushButton_19")
        self.pushButton_19.setGeometry(QRect(140, 380, 131, 41))
        self.pushButton_19.setFont(font4)
        self.pushButton_19.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_19.setStyleSheet(u"border-radius: 20px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.pushButton_19.setIconSize(QSize(200, 50))
        self.pushButton_21 = QPushButton(self.tab_7)
        self.pushButton_21.setObjectName(u"pushButton_21")
        self.pushButton_21.setGeometry(QRect(300, 380, 131, 41))
        self.pushButton_21.setFont(font4)
        self.pushButton_21.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_21.setStyleSheet(u"border-radius: 20px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.pushButton_21.setIconSize(QSize(200, 50))
        self.pushButton_20 = QPushButton(self.tab_7)
        self.pushButton_20.setObjectName(u"pushButton_20")
        self.pushButton_20.setGeometry(QRect(630, 180, 121, 41))
        self.pushButton_20.setFont(font4)
        self.pushButton_20.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_20.setStyleSheet(u"border-radius: 20px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.pushButton_20.setIconSize(QSize(200, 50))
        self.pushButton_22 = QPushButton(self.tab_7)
        self.pushButton_22.setObjectName(u"pushButton_22")
        self.pushButton_22.setGeometry(QRect(470, 180, 121, 41))
        self.pushButton_22.setFont(font4)
        self.pushButton_22.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_22.setStyleSheet(u"border-radius: 20px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.pushButton_22.setIconSize(QSize(200, 50))
        self.tableWidget_4 = QTableWidget(self.tab_7)
        if (self.tableWidget_4.columnCount() < 4):
            self.tableWidget_4.setColumnCount(4)
        __qtablewidgetitem11 = QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, __qtablewidgetitem11)
        __qtablewidgetitem12 = QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, __qtablewidgetitem12)
        __qtablewidgetitem13 = QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, __qtablewidgetitem13)
        __qtablewidgetitem14 = QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(3, __qtablewidgetitem14)
        self.tableWidget_4.setObjectName(u"tableWidget_4")
        self.tableWidget_4.setGeometry(QRect(450, 230, 311, 191))
        self.tableWidget_4.setLayoutDirection(Qt.RightToLeft)
        self.tableWidget_4.setAutoFillBackground(False)
        self.tableWidget_4.setStyleSheet(u"border: none;\n"
"background-color: #d7d6d5;\n"
"")
        self.tableWidget_4.setTextElideMode(Qt.ElideRight)
        self.textEdit = QTextEdit(self.tab_7)
        self.textEdit.setObjectName(u"textEdit")
        self.textEdit.setGeometry(QRect(450, 50, 311, 121))
        self.textEdit.setLayoutDirection(Qt.RightToLeft)
        self.radioButton = QRadioButton(self.tab_7)
        self.radioButton.setObjectName(u"radioButton")
        self.radioButton.setGeometry(QRect(500, 20, 82, 17))
        self.radioButton.setLayoutDirection(Qt.RightToLeft)
        self.radioButton_2 = QRadioButton(self.tab_7)
        self.radioButton_2.setObjectName(u"radioButton_2")
        self.radioButton_2.setGeometry(QRect(630, 20, 82, 17))
        self.radioButton_2.setLayoutDirection(Qt.RightToLeft)
        self.label_7 = QLabel(self.tab_7)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(310, 70, 131, 21))
        self.label_7.setFont(font4)
        self.spinBox_2 = QSpinBox(self.tab_7)
        self.spinBox_2.setObjectName(u"spinBox_2")
        self.spinBox_2.setGeometry(QRect(300, 130, 51, 22))
        self.spinBox_4 = QSpinBox(self.tab_7)
        self.spinBox_4.setObjectName(u"spinBox_4")
        self.spinBox_4.setGeometry(QRect(390, 130, 51, 22))
        self.label_21 = QLabel(self.tab_7)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(290, 100, 41, 21))
        self.label_21.setFont(font4)
        self.label_22 = QLabel(self.tab_7)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(390, 100, 41, 21))
        self.label_22.setFont(font4)
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.tableWidget = QTableWidget(self.tab_4)
        if (self.tableWidget.columnCount() < 1):
            self.tableWidget.setColumnCount(1)
        __qtablewidgetitem15 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, __qtablewidgetitem15)
        self.tableWidget.setObjectName(u"tableWidget")
        self.tableWidget.setGeometry(QRect(20, 20, 291, 371))
        self.tableWidget.setLayoutDirection(Qt.LeftToRight)
        self.tableWidget.setAutoFillBackground(False)
        self.tableWidget.setStyleSheet(u"border: none;\n"
"background-color: #d7d6d5;\n"
"")
        self.tableWidget.setTextElideMode(Qt.ElideRight)
        self.pushButton_6 = QPushButton(self.tab_4)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(600, 40, 161, 41))
        self.pushButton_6.setFont(font4)
        self.pushButton_6.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_6.setStyleSheet(u"border-radius: 20px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.pushButton_6.setIconSize(QSize(200, 50))
        self.pushButton_8 = QPushButton(self.tab_4)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.pushButton_8.setGeometry(QRect(180, 410, 91, 41))
        self.pushButton_8.setFont(font4)
        self.pushButton_8.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_8.setStyleSheet(u"border-radius: 20px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.pushButton_8.setIconSize(QSize(200, 50))
        self.pushButton_44 = QPushButton(self.tab_4)
        self.pushButton_44.setObjectName(u"pushButton_44")
        self.pushButton_44.setGeometry(QRect(50, 410, 91, 41))
        self.pushButton_44.setFont(font4)
        self.pushButton_44.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_44.setStyleSheet(u"border-radius: 20px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.pushButton_44.setIconSize(QSize(200, 50))
        self.pushButton_45 = QPushButton(self.tab_4)
        self.pushButton_45.setObjectName(u"pushButton_45")
        self.pushButton_45.setGeometry(QRect(340, 320, 191, 41))
        self.pushButton_45.setFont(font4)
        self.pushButton_45.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_45.setStyleSheet(u"border-radius: 20px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.pushButton_45.setIconSize(QSize(200, 50))
        self.lineEdit = QLineEdit(self.tab_4)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(340, 260, 131, 31))
        self.label_14 = QLabel(self.tab_4)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(410, 170, 47, 13))
        self.label_15 = QLabel(self.tab_4)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(430, 260, 101, 21))
        self.label_15.setFont(font4)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.pushButton_25 = QPushButton(self.tab_5)
        self.pushButton_25.setObjectName(u"pushButton_25")
        self.pushButton_25.setGeometry(QRect(620, 60, 161, 41))
        self.pushButton_25.setFont(font4)
        self.pushButton_25.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_25.setStyleSheet(u"border-radius: 20px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.pushButton_25.setIconSize(QSize(200, 50))
        self.tableWidget_5 = QTableWidget(self.tab_5)
        if (self.tableWidget_5.columnCount() < 1):
            self.tableWidget_5.setColumnCount(1)
        __qtablewidgetitem16 = QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(0, __qtablewidgetitem16)
        self.tableWidget_5.setObjectName(u"tableWidget_5")
        self.tableWidget_5.setGeometry(QRect(20, 50, 181, 371))
        self.tableWidget_5.setLayoutDirection(Qt.RightToLeft)
        self.tableWidget_5.setAutoFillBackground(False)
        self.tableWidget_5.setStyleSheet(u"border: none;\n"
"background-color: #d7d6d5;\n"
"")
        self.tableWidget_5.setTextElideMode(Qt.ElideRight)
        self.pushButton_26 = QPushButton(self.tab_5)
        self.pushButton_26.setObjectName(u"pushButton_26")
        self.pushButton_26.setGeometry(QRect(20, 440, 81, 41))
        self.pushButton_26.setFont(font4)
        self.pushButton_26.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_26.setStyleSheet(u"border-radius: 20px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.pushButton_26.setIconSize(QSize(200, 50))
        self.pushButton_27 = QPushButton(self.tab_5)
        self.pushButton_27.setObjectName(u"pushButton_27")
        self.pushButton_27.setGeometry(QRect(110, 440, 81, 41))
        self.pushButton_27.setFont(font4)
        self.pushButton_27.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_27.setStyleSheet(u"border-radius: 20px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.pushButton_27.setIconSize(QSize(200, 50))
        self.tableWidget_10 = QTableWidget(self.tab_5)
        if (self.tableWidget_10.columnCount() < 1):
            self.tableWidget_10.setColumnCount(1)
        __qtablewidgetitem17 = QTableWidgetItem()
        self.tableWidget_10.setHorizontalHeaderItem(0, __qtablewidgetitem17)
        self.tableWidget_10.setObjectName(u"tableWidget_10")
        self.tableWidget_10.setGeometry(QRect(410, 50, 171, 371))
        self.tableWidget_10.setLayoutDirection(Qt.LeftToRight)
        self.tableWidget_10.setAutoFillBackground(False)
        self.tableWidget_10.setStyleSheet(u"border: none;\n"
"background-color: #d7d6d5;\n"
"")
        self.tableWidget_10.setTextElideMode(Qt.ElideRight)
        self.pushButton_38 = QPushButton(self.tab_5)
        self.pushButton_38.setObjectName(u"pushButton_38")
        self.pushButton_38.setGeometry(QRect(510, 440, 81, 41))
        self.pushButton_38.setFont(font4)
        self.pushButton_38.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_38.setStyleSheet(u"border-radius: 20px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.pushButton_38.setIconSize(QSize(200, 50))
        self.pushButton_39 = QPushButton(self.tab_5)
        self.pushButton_39.setObjectName(u"pushButton_39")
        self.pushButton_39.setGeometry(QRect(410, 440, 81, 41))
        self.pushButton_39.setFont(font4)
        self.pushButton_39.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_39.setStyleSheet(u"border-radius: 20px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.pushButton_39.setIconSize(QSize(200, 50))
        self.pushButton_40 = QPushButton(self.tab_5)
        self.pushButton_40.setObjectName(u"pushButton_40")
        self.pushButton_40.setGeometry(QRect(310, 440, 81, 41))
        self.pushButton_40.setFont(font4)
        self.pushButton_40.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_40.setStyleSheet(u"border-radius: 20px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.pushButton_40.setIconSize(QSize(200, 50))
        self.tableWidget_11 = QTableWidget(self.tab_5)
        if (self.tableWidget_11.columnCount() < 1):
            self.tableWidget_11.setColumnCount(1)
        __qtablewidgetitem18 = QTableWidgetItem()
        self.tableWidget_11.setHorizontalHeaderItem(0, __qtablewidgetitem18)
        self.tableWidget_11.setObjectName(u"tableWidget_11")
        self.tableWidget_11.setGeometry(QRect(220, 50, 171, 371))
        self.tableWidget_11.setLayoutDirection(Qt.RightToLeft)
        self.tableWidget_11.setAutoFillBackground(False)
        self.tableWidget_11.setStyleSheet(u"border: none;\n"
"background-color: #d7d6d5;\n"
"")
        self.tableWidget_11.setTextElideMode(Qt.ElideRight)
        self.pushButton_41 = QPushButton(self.tab_5)
        self.pushButton_41.setObjectName(u"pushButton_41")
        self.pushButton_41.setGeometry(QRect(220, 440, 81, 41))
        self.pushButton_41.setFont(font4)
        self.pushButton_41.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_41.setStyleSheet(u"border-radius: 20px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.pushButton_41.setIconSize(QSize(200, 50))
        self.label_11 = QLabel(self.tab_5)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(60, 10, 81, 21))
        self.label_11.setFont(font4)
        self.label_11.setLayoutDirection(Qt.LeftToRight)
        self.label_12 = QLabel(self.tab_5)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(240, 10, 121, 21))
        self.label_12.setFont(font4)
        self.label_12.setLayoutDirection(Qt.LeftToRight)
        self.label_13 = QLabel(self.tab_5)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(460, 10, 81, 21))
        self.label_13.setFont(font4)
        self.label_13.setLayoutDirection(Qt.LeftToRight)
        self.lineEdit_3 = QLineEdit(self.tab_5)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.lineEdit_3.setGeometry(QRect(590, 200, 131, 31))
        self.label_17 = QLabel(self.tab_5)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(680, 200, 101, 21))
        self.label_17.setFont(font4)
        self.pushButton_47 = QPushButton(self.tab_5)
        self.pushButton_47.setObjectName(u"pushButton_47")
        self.pushButton_47.setGeometry(QRect(590, 250, 181, 41))
        self.pushButton_47.setFont(font4)
        self.pushButton_47.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_47.setStyleSheet(u"border-radius: 20px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.pushButton_47.setIconSize(QSize(200, 50))
        self.tabWidget.addTab(self.tab_5, "")
        self.label_4 = QLabel(self.frame)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(0, 110, 791, 491))
        self.label_4.setStyleSheet(u"background-color: rgb(128, 128, 128);")
        self.label_2 = QLabel(self.frame)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(0, 10, 131, 91))
        self.label_2.setStyleSheet(u"image: url(:/newPrefix/like pro/logo superior.png);")
        self.pushButton = QPushButton(self.frame)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(820, 300, 231, 41))
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton.setStyleSheet(u"color: rgb(0, 0, 0);\n"
"background-color: rgb(123, 123, 123);\n"
"border-radius: 20px")
        self.label_3.raise_()
        self.label.raise_()
        self.label_4.raise_()
        self.tabWidget.raise_()
        self.pushButton_5.raise_()
        self.pushButton.raise_()
        self.label_2.raise_()
        self.pushButton_48.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.pushButton_2.raise_()
        self.pushButton_24.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1091, 21))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        self.pushButton_4.setText(QCoreApplication.translate("MainWindow", u"\u0633\u062d\u0628 \u0627\u0644\u0623\u0631\u0642\u0627\u0645", None))
        self.label_3.setText("")
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"\u0627\u0644\u0625\u0631\u0633\u0627\u0644 \u0644\u0644\u0642\u0631\u0648\u0628\u0627\u062a", None))
        self.label.setText("")
        self.pushButton_24.setText(QCoreApplication.translate("MainWindow", u"\u0627\u0633\u062a\u062e\u0631\u0627\u062c \u062c\u0647\u0627\u062a \u0627\u0644\u0627\u062a\u0635\u0627\u0644", None))
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"\u0625\u0631\u0633\u0627\u0644 \u0627\u0644\u0631\u0633\u0627\u0626\u0644", None))
        self.pushButton_48.setText(QCoreApplication.translate("MainWindow", u"\u0627\u0644\u0635\u0641\u062d\u0629 \u0627\u0644\u0631\u0626\u0633\u064a\u0629", None))
        self.pushButton_5.setText(QCoreApplication.translate("MainWindow", u"\u0641\u062a\u062d \u0645\u0648\u0642\u0639 \u0627\u0644\u0648\u0627\u062a\u0633\u0627\u0628", None))
        self.label_5.setText("")
        self.lineEdit_4.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\u0623\u062f\u062e\u0644 \u0633\u064a\u0631\u064a\u0627\u0644", None))
        self.pushButton_49.setText(QCoreApplication.translate("MainWindow", u"\u0641\u062d\u0635", None))
#if QT_CONFIG(tooltip)
        self.lineEdit_5.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.lineEdit_5.setStatusTip("")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(accessibility)
        self.lineEdit_5.setAccessibleDescription("")
#endif // QT_CONFIG(accessibility)
        self.lineEdit_5.setPlaceholderText("")
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"\u062d\u0627\u0644\u0629 \u0627\u0644\u0627\u0634\u062a\u0631\u0627\u0643 :", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"\u0627\u0644\u0631\u0626\u0633\u064a\u0629", None))
        ___qtablewidgetitem = self.tableWidget_2.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"\u0627\u0644\u0631\u0642\u0645", None));
        self.pushButton_9.setText(QCoreApplication.translate("MainWindow", u"\u062c\u0644\u0628 \u0627\u0644\u0627\u0631\u0642\u0627\u0645", None))
        self.pushButton_7.setText(QCoreApplication.translate("MainWindow", u"\u0627\u0628\u062f\u0627", None))
        self.pushButton_10.setText(QCoreApplication.translate("MainWindow", u"\u0627\u064a\u0642\u0627\u0641 \u0645\u0624\u0642\u062a", None))
        self.pushButton_11.setText(QCoreApplication.translate("MainWindow", u"\u0627\u0633\u062a\u0626\u0646\u0627\u0641", None))
        self.pushButton_12.setText(QCoreApplication.translate("MainWindow", u"\u062a\u0648\u0642\u0641", None))
        self.pushButton_13.setText(QCoreApplication.translate("MainWindow", u"\u062d\u0641\u0638", None))
        self.pushButton_14.setText(QCoreApplication.translate("MainWindow", u"\u0645\u0633\u062d", None))
        ___qtablewidgetitem1 = self.tableWidget_8.horizontalHeaderItem(0)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"\u0627\u0644\u0631\u0642\u0645", None));
        ___qtablewidgetitem2 = self.tableWidget_9.horizontalHeaderItem(0)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("MainWindow", u"\u0627\u0644\u0631\u0642\u0645", None));
        self.pushButton_23.setText(QCoreApplication.translate("MainWindow", u"\u0645\u0633\u062d", None))
        self.pushButton_36.setText(QCoreApplication.translate("MainWindow", u"\u062d\u0641\u0638", None))
        self.pushButton_37.setText(QCoreApplication.translate("MainWindow", u"\u0645\u0633\u062d", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"\u062c\u0645\u064a\u0639 \u0627\u0644\u0627\u0631\u0642\u0627\u0645", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"\u0627\u0631\u0642\u0627\u0645 \u0645\u0648\u062c\u0648\u062f\u0629", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"\u0627\u0631\u0642\u0627\u0645 \u063a\u064a\u0631 \u0645\u0648\u062c\u0648\u062f\u0629", None))
        self.pushButton_42.setText(QCoreApplication.translate("MainWindow", u"\u0645\u0633\u062d", None))
        self.pushButton_43.setText(QCoreApplication.translate("MainWindow", u"\u0627\u0636\u0627\u0641\u0629", None))
        self.pushButton_46.setText(QCoreApplication.translate("MainWindow", u"\u062d\u0641\u0638 \u0628\u0635\u064a\u063a\u0629 \u0627\u0644\u0645\u0648\u0628\u064a\u0644", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"\u0627\u0644\u0627\u0633\u0645:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"\u0641\u062d\u0635 \u0627\u0644\u0627\u0631\u0642\u0627\u0645", None))
        self.pushButton_28.setText(QCoreApplication.translate("MainWindow", u"\u0627\u0636\u0627\u0641\u0647 \u0627\u0644\u0646\u0635", None))
        self.radioButton_3.setText(QCoreApplication.translate("MainWindow", u"\u0646\u0635", None))
        ___qtablewidgetitem3 = self.tableWidget_6.horizontalHeaderItem(0)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("MainWindow", u"\u0627\u0644\u0627\u0633\u0645", None));
        ___qtablewidgetitem4 = self.tableWidget_6.horizontalHeaderItem(1)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("MainWindow", u"\u0627\u0644\u062d\u0627\u0644\u0629", None));
        self.pushButton_29.setText(QCoreApplication.translate("MainWindow", u"\u062c\u0644\u0628 \u0627\u0644\u0627\u0633\u0645\u0627\u0621", None))
        ___qtablewidgetitem5 = self.tableWidget_7.horizontalHeaderItem(0)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("MainWindow", u"\u0627\u0644\u0646\u0635", None));
        ___qtablewidgetitem6 = self.tableWidget_7.horizontalHeaderItem(1)
        ___qtablewidgetitem6.setText(QCoreApplication.translate("MainWindow", u"\u0645\u0631\u0641\u0642", None));
        ___qtablewidgetitem7 = self.tableWidget_7.horizontalHeaderItem(2)
        ___qtablewidgetitem7.setText(QCoreApplication.translate("MainWindow", u"\u0627\u0644\u0646\u0648\u0639", None));
        self.pushButton_30.setText(QCoreApplication.translate("MainWindow", u"\u0627\u0628\u062f\u0627", None))
        self.radioButton_4.setText(QCoreApplication.translate("MainWindow", u"\u0635\u0648\u0631\u0647", None))
        self.pushButton_31.setText(QCoreApplication.translate("MainWindow", u"\u0627\u064a\u0642\u0627\u0641 \u0645\u0624\u0642\u062a", None))
        self.pushButton_32.setText(QCoreApplication.translate("MainWindow", u"\u0627\u0636\u0627\u0641\u0629 \u0635\u0648\u0631\u0647", None))
        self.pushButton_33.setText(QCoreApplication.translate("MainWindow", u"\u0627\u0633\u062a\u0626\u0646\u0627\u0641", None))
        self.pushButton_34.setText(QCoreApplication.translate("MainWindow", u"\u0645\u0633\u062d", None))
        self.pushButton_35.setText(QCoreApplication.translate("MainWindow", u"\u062a\u0648\u0642\u0641", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"\u0627\u0644\u0641\u0627\u0635\u0644 \u0627\u0644\u0632\u0645\u0646\u064a:", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"\u0645\u0646", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"\u0627\u0644\u064a", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"\u0627\u0631\u0633\u0627\u0644 \u0644\u0644\u062c\u0631\u0648\u0628\u0627\u062a", None))
        ___qtablewidgetitem8 = self.tableWidget_3.horizontalHeaderItem(0)
        ___qtablewidgetitem8.setText(QCoreApplication.translate("MainWindow", u"\u0627\u0644\u0631\u0642\u0645", None));
        ___qtablewidgetitem9 = self.tableWidget_3.horizontalHeaderItem(1)
        ___qtablewidgetitem9.setText(QCoreApplication.translate("MainWindow", u"\u0627\u0644\u062d\u0627\u0644\u0629", None));
        self.pushButton_15.setText(QCoreApplication.translate("MainWindow", u"\u0627\u0628\u062f\u0627", None))
        self.pushButton_16.setText(QCoreApplication.translate("MainWindow", u"\u0627\u0633\u062a\u0626\u0646\u0627\u0641", None))
        self.pushButton_17.setText(QCoreApplication.translate("MainWindow", u"\u0627\u064a\u0642\u0627\u0641 \u0645\u0624\u0642\u062a", None))
        self.pushButton_18.setText(QCoreApplication.translate("MainWindow", u"\u0645\u0633\u062d", None))
        self.pushButton_19.setText(QCoreApplication.translate("MainWindow", u"\u062c\u0644\u0628 \u0627\u0644\u0627\u0631\u0642\u0627\u0645", None))
        self.pushButton_21.setText(QCoreApplication.translate("MainWindow", u"\u062a\u0648\u0642\u0641", None))
        self.pushButton_20.setText(QCoreApplication.translate("MainWindow", u"\u0627\u0636\u0627\u0641\u0647 \u0627\u0644\u0646\u0635", None))
        self.pushButton_22.setText(QCoreApplication.translate("MainWindow", u"\u0627\u0636\u0627\u0641\u0629 \u0635\u0648\u0631\u0647", None))
        ___qtablewidgetitem10 = self.tableWidget_4.horizontalHeaderItem(0)
        ___qtablewidgetitem10.setText(QCoreApplication.translate("MainWindow", u"\u0627\u0644\u0646\u0635", None));
        ___qtablewidgetitem11 = self.tableWidget_4.horizontalHeaderItem(1)
        ___qtablewidgetitem11.setText(QCoreApplication.translate("MainWindow", u"\u0645\u0631\u0641\u0642", None));
        ___qtablewidgetitem12 = self.tableWidget_4.horizontalHeaderItem(2)
        ___qtablewidgetitem12.setText(QCoreApplication.translate("MainWindow", u"\u0627\u0644\u0646\u0648\u0639", None));
        self.radioButton.setText(QCoreApplication.translate("MainWindow", u"\u0635\u0648\u0631\u0647", None))
        self.radioButton_2.setText(QCoreApplication.translate("MainWindow", u"\u0646\u0635", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"\u0627\u0644\u0641\u0627\u0635\u0644 \u0627\u0644\u0632\u0645\u0646\u064a:", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"\u0627\u0644\u064a", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"\u0645\u0646", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), QCoreApplication.translate("MainWindow", u"\u0627\u0631\u0633\u0627\u0644 \u0644\u0644\u0627\u0631\u0642\u0627\u0645", None))
        ___qtablewidgetitem13 = self.tableWidget.horizontalHeaderItem(0)
        ___qtablewidgetitem13.setText(QCoreApplication.translate("MainWindow", u"\u0627\u0644\u0631\u0642\u0645", None));
        self.pushButton_6.setText(QCoreApplication.translate("MainWindow", u"\u0628\u062f\u0623 \u0633\u062d\u0628", None))
        self.pushButton_8.setText(QCoreApplication.translate("MainWindow", u"\u062d\u0641\u0638", None))
        self.pushButton_44.setText(QCoreApplication.translate("MainWindow", u"\u062d\u0630\u0641", None))
        self.pushButton_45.setText(QCoreApplication.translate("MainWindow", u"\u062d\u0641\u0638 \u0628\u0635\u064a\u063a\u0629 \u0627\u0644\u0645\u0648\u0628\u064a\u0644", None))
        self.label_14.setText("")
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"\u0627\u0644\u0627\u0633\u0645:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QCoreApplication.translate("MainWindow", u"\u0633\u062d\u0628 \u0627\u0644\u0627\u0631\u0642\u0627\u0645", None))
        self.pushButton_25.setText(QCoreApplication.translate("MainWindow", u"\u0627\u0628\u062f\u0623 \u0633\u062d\u0628 ", None))
        ___qtablewidgetitem14 = self.tableWidget_5.horizontalHeaderItem(0)
        ___qtablewidgetitem14.setText(QCoreApplication.translate("MainWindow", u"\u0627\u0644\u0627\u0633\u0645", None));
        self.pushButton_26.setText(QCoreApplication.translate("MainWindow", u"\u062d\u0641\u0638", None))
        self.pushButton_27.setText(QCoreApplication.translate("MainWindow", u"\u062d\u0630\u0641", None))
        ___qtablewidgetitem15 = self.tableWidget_10.horizontalHeaderItem(0)
        ___qtablewidgetitem15.setText(QCoreApplication.translate("MainWindow", u"\u0627\u0644\u0631\u0642\u0645", None));
        self.pushButton_38.setText(QCoreApplication.translate("MainWindow", u"\u062d\u0630\u0641", None))
        self.pushButton_39.setText(QCoreApplication.translate("MainWindow", u"\u062d\u0641\u0638", None))
        self.pushButton_40.setText(QCoreApplication.translate("MainWindow", u"\u062d\u0630\u0641", None))
        ___qtablewidgetitem16 = self.tableWidget_11.horizontalHeaderItem(0)
        ___qtablewidgetitem16.setText(QCoreApplication.translate("MainWindow", u"\u0627\u0644\u0627\u0633\u0645", None));
        self.pushButton_41.setText(QCoreApplication.translate("MainWindow", u"\u062d\u0641\u0638", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"\u0627\u0644\u0642\u0631\u0648\u0628\u0627\u062a", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"\u062c\u0647\u0627\u062a \u0627\u0644\u0627\u062a\u0635\u0627\u0644", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"\u0627\u0644\u0627\u0631\u0642\u0627\u0645", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"\u0627\u0644\u0627\u0633\u0645:", None))
        self.pushButton_47.setText(QCoreApplication.translate("MainWindow", u"\u062d\u0641\u0638 \u0628\u0635\u064a\u063a\u0629 \u0627\u0644\u0645\u0648\u0628\u064a\u0644", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QCoreApplication.translate("MainWindow", u"\u0633\u062d\u0628 \u062c\u0647\u0627\u062a \u0627\u0644\u0627\u062a\u0635\u0627\u0644", None))
        self.label_4.setText("")
        self.label_2.setText("")
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"\u0627\u062e\u062a\u0628\u0627\u0631 \u0627\u0644\u0627\u0631\u0642\u0627\u0645", None))
        pass
    # retranslateUi

